function y = untitled(x)
%UNTITLED Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 19-May-2015 11:13:46

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 16000;  % First Stopband Frequency
    % Fpass1 = 18000;  % First Passband Frequency
    % Fpass2 = 22000;  % Second Passband Frequency
    % Fstop2 = 24000;  % Second Stopband Frequency
    % Astop1 = 60;     % First Stopband Attenuation (dB)
    % Apass  = 1;      % Passband Ripple (dB)
    % Astop2 = 80;     % Second Stopband Attenuation (dB)
    % Fs     = 48000;  % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'MatchExactly', 'both', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 1.14130293119043 1 1 1.39867674284504 ...
        0.976198353627479; 1 1.95695352212123 1 1 1.92317900396872 ...
        0.991202579820827; 1 0.969334586738702 1 1 1.43355782785495 ...
        0.924448288236785; 1 1.96602156745554 1 1 1.88917323929073 ...
        0.967630153951403; 1 0.213472842463069 1 1 1.53496489030976 ...
        0.877210551971112; 1 1.98531634371046 1 1 1.81581515263497 ...
        0.926776752446677; 1 0 -1 1 1.68428051313771 0.878570812410099], ...
        'ScaleValues', [0.34111474859417; 0.34111474859417; ...
        0.509536929090346; 0.509536929090346; 0.221122765467523; ...
        0.221122765467523; 0.251680766054981; 1]);
end

y = step(Hd,x);


